spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/domain9065/hello-spring-cloud.git
          search-paths: hello-spring-cloud-config/src/main/resources
          username: domain9065
          password: 888chinaunicom

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/